# Default values for piwhelm.
global:
  piwhelm: # to be replaced with chart name
    secrets: # Secrets configuration section
      imageCredentials: # Credentials secrets configuration section (optional)
        name: my-credentials # required if enabled
        enabled: true # set to true to render image pull secret
        registry: quay.io # required if enabled
        username: someone # required if enabled
        password: sillyness # required if enabled
        email: someone@host.com # required if enabled
      otherSecrets:
        - name: secret1 # required if enabled
          enabled: true # set to true to render this secret
          type: Opaque # defaults to Opaque if not specified
          data: # key-value pairs, values will be base64 encoded
            secretkey1: value1
            secretkey2: value2
        - name: secret2
          enabled: false # not rendered if false
          type: Opaque
          data:
            secretkey3: value3
            secretkey4: value4
      externalSecrets: # External secrets configuration section (optional)
        - name: external-secret-1 # required
          apiVersion: external-secrets.io/v1 # defaults to external-secrets.io/v1 if not specified
          kind: ClusterSecretStore # defaults to ClusterSecretStore if not specified
          storeName: kubernetes # defaults to kubernetes if not specified
          data:
            - secretKey: API_TOKEN # required
              remoteRef:
                key: my-secret-ref-name-1 # required
                property: credential # required
            - secretKey: EMAIL
              remoteRef:
                key: my-secret-ref-name-1
                property: email
            - secretKey: DOMAIN
              remoteRef:
                key: my-secret-ref-name-1
                property: domain
    deployment: # Deployment configuration section
      enabled: true
      name: piwhelm
      apiVersion: apps/v1
      replicas: 1
      nodeSelector: # Node selector for deployment
        device: raspi
      containers: # Containers configuration section
        - name: container-1
          enabled: true
          image: docker-image-1
          imagePullPolicy: ""
          securityContext: # Container security context (optional)
            capabilities:
              add: [ "NET_ADMIN" ]
          envFrom: # Environment variables from ConfigMap (optional)
            - configMapRef:
                name: configmap-name # To match with configMap.name below
          ports: # Container ports (optional)
            - name: name-port-example
              containerPort: 8888
              protocol: TCP # Protocol (optional)
          volumeMounts: # Volume mounts (optional)
            - name: volume-example
              mountPath: path/to/volume
      volumes: # Volumes for deployment (optional)
        - name: log-volume
          emptyDir: true # Create an emptyDir volume
        - name: name-volume
          persistentVolumeClaim: pvc-claim-name

    configMap: # ConfigMap configuration section (optional)
      name: configmap-name
      enabled: true

    services: # Kubernetes services configuration section (optional)
      - name: ""
        enabled: false
        type: ClusterIP
        ports: # Service ports
          - name: http
            protocol: TCP
            port: 80
            targetPort: 0000
          - name: https
            protocol: TCP
            port: 443
            targetPort: 0000

    pvs: # PersistentVolumes configuration section (optional)
      - name: ""
        enabled: false
        storageClassName: ""
        capacity:
          storage: 1Gi
        accessModes: [ReadWriteMany]
        persistentVolumeReclaimPolicy: Retain
        nfs:
          path: ""
          server: ""
          readOnly: false

    pvcs: # PersistentVolumeClaims configuration section (optional)
    - name: ""
      enabled: false
      storageClassName: ""
      volumeName: ""
      accessModes: [ReadWriteMany]
      volumeMode: Filesystem
      storage: 1Gi

    ingressroutes: # Ingress routes configuration section (optional)
      - name: ""
        apiVersion: traefik.io/v1alpha1
        enabled: false
        serviceName: ""
        entryPoints:
          - web
          - websecure
        routes:
          - match: Host(`your_domain.com`)
            enabled: true
            kind: Rule
            middlewares: [ ]
            services:
              - kind: Service
                enabled: true
                name: service_name
                namespace: ""
                port: 80
    extraLabels: # Extra labels for all the manifests (optional)
#      label1: value1
#      label2: value2