# Default values for piwhelm.
global:
  piwhelm: # to be replaced with chart name
    configMap:
      name: ""
    services:
      - name: ""
        enabled: true
        type: ClusterIP
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 0000
          - name: https
            protocol: TCP
            port: 443
            targetPort: 0000
    pvs:
      - name: ""
        enabled: true
        storageClassName: ""
        capacity:
          storage: 1Gi
        accessmodes:
          accessModes:
            - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        nfs:
          path: ""
          server: ""
          readOnly: false
    pvcs:
    - name: ""
      enabled: true
      storageClassName: ""
      volumeName: ""
      accessModes: [ReadWriteMany]
      volumeMode: Filesystem
      storage: 1Gi
