# Default values for piwhelm.
global:
  piwhelm: # to be replaced with chart name
    configMap:
      name: ""
    services:
      - name: ""
        enabled: true
        type: ClusterIP
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 0000

          - name: https
            protocol: TCP
            port: 443
            targetPort: 0000

    deployment:

