# Default values for piwhelm.
global:
  piwhelm: # to be replaced with chart name
    configMap:
      name: ""
      enabled: false

    services:
      - name: ""
        enabled: false
        type: ClusterIP
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 0000
          - name: https
            protocol: TCP
            port: 443
            targetPort: 0000

    pvs:
      - name: ""
        enabled: false
        storageClassName: ""
        capacity:
          storage: 1Gi
        accessmodes:
          accessModes:
            - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        nfs:
          path: ""
          server: ""
          readOnly: false

    pvcs:
    - name: ""
      enabled: false
      storageClassName: ""
      volumeName: ""
      accessModes: [ReadWriteMany]
      volumeMode: Filesystem
      storage: 1Gi

    ingressroutes:
      - name: ""
        apiVersion: traefik.io/v1alpha1
        enabled: false
        serviceName: ""
        entryPoints:
          - web
          - websecure
        routes:
          - match: Host(`your_domain.com`)
            enabled: true
            kind: Rule
            middlewares: [ ]
            services:
              - kind: Service
                enabled: true
                name: service_name
                namespace: ""
                port: 80